export default function CreatorAgreement() {
  const sectionStyle = {
    fontFamily: "Arial",
    fontSize: "11px",
    letterSpacing: "3px",
    color: "#c9a96e",
    textTransform: "uppercase" as const,
    margin: "40px 0 12px",
  };

  const body = {
    fontFamily: "Georgia, serif",
    fontSize: "15px",
    color: "rgba(255,255,255,0.65)",
    lineHeight: "1.9",
    margin: "0 0 12px",
  };

  const bullet = {
    fontFamily: "Georgia, serif",
    fontSize: "15px",
    color: "rgba(255,255,255,0.65)",
    lineHeight: "1.9",
    margin: "0 0 8px",
    paddingLeft: "20px",
  };

  const caps = {
    fontFamily: "Georgia, serif",
    fontSize: "13px",
    color: "rgba(255,255,255,0.55)",
    lineHeight: "1.8",
    margin: "0 0 12px",
  };

  return (
    <div style={{ minHeight: "100vh", backgroundColor: "#0a0a0a", color: "white", padding: "60px 24px", maxWidth: "720px", margin: "0 auto" }}>
      <p style={{ fontFamily: "Arial", fontSize: "11px", letterSpacing: "4px", color: "#c9a96e", textTransform: "uppercase", marginBottom: "16px" }}>Legal</p>
      <h1 style={{ fontFamily: "Arial", fontSize: "28px", fontWeight: "700", letterSpacing: "4px", color: "white", margin: "0 0 8px" }}>Creator Agreement</h1>
      <p style={{ fontFamily: "Georgia, serif", fontSize: "13px", color: "rgba(255,255,255,0.35)", marginBottom: "4px" }}>Effective Date: June 3, 2026 | Version 1.0</p>
      <div style={{ width: "40px", height: "2px", backgroundColor: "#c9a96e", margin: "24px 0 32px" }} />

      <p style={{ ...body, fontStyle: "italic", color: "rgba(255,255,255,0.5)" }}>Please read this Agreement carefully before registering as a Creator. By clicking "I Agree," completing registration, or using the Platform in any capacity, you acknowledge that you have read, understood, and agree to be legally bound by this Agreement.</p>

      <p style={sectionStyle}>Section 1. Definitions</p>
      <p style={body}>As used in this Creator Agreement, the following terms have the meanings set forth below:</p>
      <p style={bullet}>— <strong style={{ color: "rgba(255,255,255,0.85)" }}>Agreement</strong> — this Creator Agreement, together with all policies and documents incorporated by reference, including the Terms of Service and Privacy Policy.</p>
      <p style={bullet}>— <strong style={{ color: "rgba(255,255,255,0.85)" }}>Brand</strong> — any company, business owner, individual, or entity registered on the Platform seeking content creation, influencer marketing, promotional, or advertising services.</p>
      <p style={bullet}>— <strong style={{ color: "rgba(255,255,255,0.85)" }}>Campaign / Deal</strong> — an agreed engagement, project, or service arrangement between a Brand and a Creator initiated, documented, and managed through the Platform.</p>
      <p style={bullet}>— <strong style={{ color: "rgba(255,255,255,0.85)" }}>Content</strong> — any photographs, videos, reels, short-form videos, stories, posts, written copy, audio recordings, graphics, animations, synthetic media, AI-generated materials, or other creative materials produced or delivered in connection with a Campaign.</p>
      <p style={bullet}>— <strong style={{ color: "rgba(255,255,255,0.85)" }}>Creator</strong> — any individual or entity registered on the Platform to offer content creation, influencer marketing, social media posting, user-generated content (UGC), photography, videography, or promotional services.</p>
      <p style={bullet}>— <strong style={{ color: "rgba(255,255,255,0.85)" }}>FTC Endorsement Guides</strong> — the FTC's Guides Concerning the Use of Endorsements and Testimonials in Advertising, as amended from time to time (16 C.F.R. Part 255).</p>
      <p style={bullet}>— <strong style={{ color: "rgba(255,255,255,0.85)" }}>Introduced Brand</strong> — any Brand with which Creator first established contact, communication, or a business relationship through or by means of the Platform.</p>
      <p style={bullet}>— <strong style={{ color: "rgba(255,255,255,0.85)" }}>Platform</strong> — the PearUp website, mobile application, software, tools, APIs, marketplace infrastructure, and all related services operated by PearUp.</p>
      <p style={bullet}>— <strong style={{ color: "rgba(255,255,255,0.85)" }}>Platform Fee</strong> — the twelve percent (12%) commission charged by PearUp on each completed transaction.</p>
      <p style={bullet}>— <strong style={{ color: "rgba(255,255,255,0.85)" }}>Services</strong> — the content creation, influencer marketing, promotional, social media, UGC, and related services provided by Creator to Brands through the Platform.</p>

      <p style={sectionStyle}>Section 2. Nature of the Platform & Pearup's Role</p>
      <p style={body}>PearUp is a technology marketplace and intermediary platform only. PearUp's sole role is to provide the technical infrastructure connecting Brands with Creators, facilitate communication and Campaign creation, process payments and disburse funds, and provide tools to support Campaign management.</p>
      <p style={body}>PearUp does not employ, supervise, direct, control, manage, endorse, or represent any Creator or Brand. PearUp is not a staffing agency, talent agency, advertising agency, marketing firm, publisher, media company, joint venture partner, or fiduciary of any kind.</p>
      <p style={body}>PearUp does not pre-screen, review, approve, verify, or monitor any Content, Campaign, or Creator conduct. PearUp does not verify Creator's follower counts, engagement rates, audience demographics, or any other social media statistics. PearUp does not assess or confirm Creator's compliance with any applicable law, including the FTC Endorsement Guides. PearUp's provision of the Platform does not constitute participation in, endorsement of, or responsibility for any Campaign or Content.</p>

      <p style={sectionStyle}>Section 3. Independent Contractor Status</p>
      <p style={body}>Creator is an independent contractor. Nothing in this Agreement creates or implies any employment relationship, agency relationship authorizing Creator to bind PearUp to any obligation, partnership, joint venture, franchise, or fiduciary relationship between PearUp and Creator. Creator has no authority, express or implied, to make any representation, warranty, or commitment on behalf of PearUp. Creator shall not hold themselves out as an employee, agent, partner, or representative of PearUp.</p>
      <p style={body}>As an independent contractor, Creator is solely and exclusively responsible for: all federal, state, local, and international income taxes, self-employment taxes, payroll taxes, sales taxes, and any other taxes arising from Creator's income or activities; obtaining and maintaining all business licenses, permits, registrations, and professional certifications required by applicable law; obtaining and maintaining all necessary insurance coverage; compliance with all applicable labor, employment, immigration, and worker classification laws; all regulatory compliance obligations, including advertising disclosure requirements; and all equipment, software, subscriptions, and operational costs incurred in performing Services.</p>

      <p style={sectionStyle}>Section 4. Eligibility & Registration</p>
      <p style={body}>To register as a Creator and use the Platform, you must: be at least eighteen (18) years of age or the age of majority in your jurisdiction; have the legal capacity and authority to enter into binding contracts; not be prohibited from using the Platform under applicable law; complete the registration process accurately and completely; and not be a person or entity subject to applicable economic sanctions, embargoes, or other trade restrictions.</p>
      <p style={body}>By registering, you represent, warrant, and covenant that: all information provided during registration and throughout your use of the Platform is, and will remain, accurate, current, truthful, and complete; all social media metrics, follower counts, engagement rates, audience demographics, reach statistics, and performance data disclosed on your profile are truthful, accurately calculated, and not misleading; you will promptly update your profile to reflect any material changes; you will not create duplicate or multiple accounts for any purpose; you will not transfer, sell, or assign your account to any other person or entity; and you will maintain active, compliant accounts on all social media platforms represented in your profile.</p>
      <p style={body}>Deliberate or material misrepresentation of any information during registration or thereafter is grounds for immediate and permanent account termination without notice and without liability to PearUp.</p>

      <p style={sectionStyle}>Section 5. Creator Representations & Warranties</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Identity & Authority</strong> — Creator has full legal right, power, and authority to enter into this Agreement and perform all obligations hereunder. This Agreement constitutes a valid, binding, and enforceable obligation of Creator. Creator's execution and performance of this Agreement does not violate or conflict with any other agreement, obligation, order, judgment, or law to which Creator is subject.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Authenticity of Social Media Presence</strong> — All follower counts, subscriber counts, engagement rates, view counts, impression statistics, click-through rates, and reach data displayed on Creator's profile are authentic and accurately represent Creator's genuine, organic social media presence. Creator has not purchased and will not purchase followers, likes, comments, shares, views, or any other form of social media engagement. Creator does not use and has never used bots, automated engagement tools, click farms, engagement pods (to the extent designed to artificially inflate metrics), or any other mechanism to artificially inflate any social media metric. Creator's audience consists of genuine human users.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Content Representations</strong> — With respect to all Content delivered or published in connection with any Campaign, Creator represents and warrants that: all Content is Creator's original work or Creator possesses all rights, licenses, consents, and permissions necessary to use, deliver, and license such Content; all Content was created lawfully and in compliance with all applicable laws and regulations; Creator is the exclusive owner of all Intellectual Property rights in and to all original Content, or Creator possesses valid and sufficient licenses from the rightful owner(s); no Content infringes, misappropriates, or violates any Intellectual Property right, publicity right, privacy right, or moral right of any third party; no Content contains any material that is defamatory, obscene, fraudulent, deceptive, misleading, or otherwise unlawful; all claims, statements, endorsements, and testimonials contained in Content are truthful, non-deceptive, substantiated where required by law, and based on Creator's genuine opinion and experience; and Creator has obtained all necessary clearances, consents, and releases from all individuals appearing in Content.</p>

      <p style={sectionStyle}>Section 6. Intellectual Property Rights & Content Clearances</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Creator Ownership</strong> — Creator retains full ownership of all original Content created by Creator. No transfer of copyright in Creator's Content to PearUp occurs solely by virtue of this Agreement.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>License to PearUp</strong> — By using the Platform, Creator grants PearUp a non-exclusive, worldwide, royalty-free, sublicensable, transferable license to host, store, display, transmit, process, reproduce, and use Creator's Content and profile materials solely to the extent necessary to operate, improve, promote, and provide the Platform, subject to PearUp's Privacy Policy.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>License to Brands</strong> — Upon full payment for a Campaign, and unless a different scope is expressly negotiated in the applicable Campaign terms, Creator grants the Brand a limited, non-exclusive, non-transferable license to use the delivered Content on the Brand's own marketing channels for a period of one (1) year. This default license does not include: (a) the right to use Content in paid advertising, dark posts, whitelisting, or boosted posts without Creator's express written consent; (b) the right to modify, alter, or create derivative works without Creator's consent; or (c) the right to sublicense, sell, or transfer Content to third parties.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Music & Audio</strong> — All music, sound recordings, and audio elements incorporated in any video, reel, or other audiovisual Content must be fully cleared for all contemplated uses, including synchronization rights, master rights, and performance rights, through valid licenses or through use of royalty-free or original compositions. Creator acknowledges that platform-licensed music (e.g., Instagram Music, TikTok Sound Library) may only be used pursuant to the specific terms of those platforms and may not carry over to other uses, including Brand advertising.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>AI-Generated Content</strong> — Creator shall clearly disclose to both PearUp and the Brand, at the time of Content delivery, if any portion of the delivered Content was generated, created, or substantially modified using artificial intelligence tools, generative AI platforms, large language models, image synthesis models, video synthesis models, voice synthesis tools, or any other AI-based creative technology. Creator represents and warrants that any AI-generated Content does not infringe any third-party Intellectual Property rights and does not constitute a deepfake or synthetic media depicting any real, identifiable individual without that individual's express written consent. Creator shall not represent AI-generated Content as wholly human-created without appropriate disclosure.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Publicity & Privacy Rights</strong> — Creator has obtained all necessary written consents, model releases, and property releases from all individuals whose name, image, likeness, voice, signature, persona, or private information appears in or is referenced by any Content. No Content violates any individual's right of publicity, right of privacy, or personality rights under applicable law.</p>
      <p style={body}>Creator shall defend, indemnify, and hold harmless PearUp and all Brands from and against all losses, damages, costs, and expenses (including reasonable attorneys' fees) arising from any breach of the representations and warranties in this Section 6.</p>

      <p style={sectionStyle}>Section 7. FTC Compliance & Advertising Disclosure</p>
      <p style={body}>Creator is solely, exclusively, and fully responsible for complying with all applicable advertising disclosure laws, consumer protection laws, and truth-in-advertising requirements applicable to Creator's Content and activities, including without limitation: the Federal Trade Commission Act and all FTC regulations; the FTC Endorsement Guides (16 C.F.R. Part 255); all state consumer protection statutes and advertising laws; and all applicable rules, policies, and guidelines of each social media platform on which Creator publishes sponsored Content.</p>
      <p style={body}>Creator must, in connection with every Campaign and every piece of sponsored, paid, gifted, or otherwise compensated Content:</p>
      <p style={bullet}>— Include a clear, conspicuous, and unambiguous disclosure of the material relationship between Creator and the Brand, placed where it will be easily noticed by the audience before they engage with the Content.</p>
      <p style={bullet}>— Use disclosure language that complies with current FTC and applicable regulatory guidance, including language such as "#ad," "#sponsored," "#paid," "Paid partnership with [Brand]," "Advertisement," or equivalent clear and unambiguous disclosures.</p>
      <p style={bullet}>— Ensure disclosures are not buried within a list of hashtags, below "more" links, in fine print, or in any other placement where they are unlikely to be noticed.</p>
      <p style={bullet}>— Include disclosures in every piece of Content that mentions, features, or endorses the Brand's product or service, including stories, reels, posts, YouTube videos, podcasts, and any other Content format.</p>
      <p style={bullet}>— Not remove or obscure disclosures after Content is published without the Brand's written consent and without replacing them with equivalent language.</p>
      <p style={bullet}>— Disclose all material connections to the Brand, including: cash compensation, free products, gifts, discounts, affiliate commissions, equity interests, employment relationships, and any other consideration of value.</p>
      <p style={body}>Creator shall not make any objective claim about a Brand's product or service unless Creator has a reasonable basis for such claim, has personally experienced the claimed benefit, and the claim is consistent with the Brand's truthful advertising materials.</p>
      <p style={caps}>PEARUP IS NOT RESPONSIBLE FOR REVIEWING, APPROVING, OR ENSURING THE COMPLIANCE OF CREATOR'S CONTENT WITH FTC REQUIREMENTS OR ANY ADVERTISING DISCLOSURE LAW. PEARUP SHALL BEAR NO LIABILITY WHATSOEVER FOR ANY CREATOR'S FAILURE TO INCLUDE REQUIRED DISCLOSURES, FOR ANY CREATOR'S DECEPTIVE ADVERTISING PRACTICES, OR FOR ANY FINES, PENALTIES, ENFORCEMENT ACTIONS, OR CIVIL LIABILITY ARISING FROM CREATOR'S NON-COMPLIANCE WITH ADVERTISING LAWS. ANY REGULATORY ENFORCEMENT ACTION, CIVIL CLAIM, OR OTHER CONSEQUENCE ARISING FROM CREATOR'S ADVERTISING DISCLOSURES OR LACK THEREOF IS SOLELY CREATOR'S RESPONSIBILITY.</p>

      <p style={sectionStyle}>Section 8. Creator Service Obligations</p>
      <p style={body}>Creator agrees that in connection with each Campaign accepted through the Platform, Creator shall:</p>
      <p style={bullet}>— Deliver all agreed Content and Services within the timeframes specified in the Campaign terms.</p>
      <p style={bullet}>— Create Content that materially conforms to the scope, specifications, creative brief, and requirements agreed upon in the Campaign.</p>
      <p style={bullet}>— Communicate promptly with the Brand and with PearUp regarding any circumstances that may prevent Creator from meeting a deadline or fulfilling any Campaign obligation.</p>
      <p style={bullet}>— Maintain professional standards of conduct in all communications with Brands.</p>
      <p style={bullet}>— Post Content only on the social media platforms and accounts specified in the Campaign terms.</p>
      <p style={bullet}>— Not accept payment outside the Platform for any Campaign or Brand relationship originated through the Platform.</p>
      <p style={bullet}>— Not subcontract, outsource, or delegate the performance of any material Campaign obligation to any third party without the Brand's prior written consent.</p>
      <p style={bullet}>— Retain and preserve all original files, raw materials, and supporting documentation related to Content deliverables for a period of not less than three (3) years following Campaign completion.</p>
      <p style={body}>Creator acknowledges that audience reach, engagement metrics, traffic, conversions, revenue, and other commercial results of a Campaign cannot be guaranteed by Creator or PearUp, and are dependent on numerous factors outside Creator's control, including platform algorithm changes, audience behavior, and Brand's product quality.</p>

      <p style={sectionStyle}>Section 9. Platform Fee & Payment Terms</p>
      <p style={body}>PearUp charges a Platform Fee equal to twelve percent (12%) of the total value of each Campaign completed through the Platform. This fee is automatically deducted at the time of payment release. The Platform Fee is non-negotiable and non-refundable under any circumstances, including in the event of a dispute, partial refund, or account termination, provided that the Campaign was marked active prior to such event.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Payment Release Timeline</strong> — Following completion and delivery of agreed Content or Services: the Brand has forty-eight (48) hours to review the Content and file a dispute if the Content materially fails to conform to the agreed Campaign terms; if no dispute is filed within 48 hours, payment will be automatically released to Creator, less the applicable Platform Fee; Creator payouts will be processed within three (3) to five (5) business days after the 48-hour review period closes without a filed dispute. PearUp is not responsible for delays caused by payment processor issues, bank processing times, incorrect account information provided by Creator, or force majeure events.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Tax Obligations</strong> — Creator is solely and exclusively responsible for determining and satisfying all federal, state, local, and international tax obligations arising from income earned through the Platform, including income taxes, self-employment taxes, sales taxes, and value-added taxes. PearUp does not withhold taxes on behalf of Creators. Creators who earn $600 USD or more in a single calendar year through the Platform may receive IRS Form 1099-NEC and will be required to provide a completed Form W-9 or equivalent documentation upon request. Failure to provide required tax documentation may result in backup withholding or suspension of Creator's account.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Disputed Chargebacks</strong> — If a Brand initiates an unauthorized chargeback after a Campaign has been completed and Content delivered in accordance with agreed Campaign terms, PearUp reserves the right to permanently suspend the Brand's account, recover any Platform Fees and related processing costs, reverse any payment to Creator pending resolution of the chargeback, and pursue all available legal remedies. Creator agrees to cooperate with PearUp in contesting any fraudulent or bad-faith chargeback.</p>

      <p style={sectionStyle}>Section 10. Content Standards & Prohibited Content</p>
      <p style={body}>All Content created or published in connection with any Campaign shall comply with all applicable laws and regulations, all Platform policies, all applicable social media platform community guidelines, and the content standards set forth herein. The following categories of Content are strictly prohibited on the Platform and in connection with any Campaign:</p>
      <p style={bullet}>— Misleading, deceptive, or false statements about a product's characteristics, benefits, efficacy, safety, or origin.</p>
      <p style={bullet}>— Defamatory, libelous, or slanderous Content.</p>
      <p style={bullet}>— Content that promotes, glorifies, or incites hatred, discrimination, harassment, or violence based on race, ethnicity, national origin, religion, gender, gender identity, sexual orientation, disability, age, or any other protected characteristic.</p>
      <p style={bullet}>— Content that harasses, intimidates, threatens, or demeans any individual.</p>
      <p style={bullet}>— Pornographic, obscene, or sexually explicit Content; Content that sexualizes minors in any manner.</p>
      <p style={bullet}>— Content promoting or facilitating the sale or distribution of illegal products, controlled substances, drug paraphernalia, counterfeit goods, or weapons.</p>
      <p style={bullet}>— Content promoting gambling, sports betting, binary options, unlicensed financial products, cryptocurrency investment schemes, or financial speculation without appropriate regulatory disclosures and licensing.</p>
      <p style={bullet}>— Content making unauthorized medical claims, promoting prescription drugs for off-label use, or making false or misleading health claims.</p>
      <p style={bullet}>— Content promoting any investment opportunity, security, initial coin offering, or financial product in a manner that violates applicable securities laws or constitutes fraud.</p>
      <p style={bullet}>— Content promoting multi-level marketing programs or pyramid schemes in a deceptive or non-compliant manner.</p>
      <p style={bullet}>— Content glorifying, inciting, or providing instructions for violence, self-harm, illegal dangerous activities, or terrorism.</p>
      <p style={bullet}>— Content disclosing the private information of any individual without their consent.</p>
      <p style={bullet}>— Content that impersonates any individual, company, organization, or government entity in a manner likely to deceive.</p>
      <p style={bullet}>— Content that infringes any third-party copyright, trademark, patent, trade secret, or other Intellectual Property right.</p>
      <p style={body}>PearUp reserves the right, in its sole and absolute discretion and without prior notice, to remove, take down, flag, restrict, or disable any Content that PearUp determines violates this Agreement, the Terms of Service, any applicable law or regulation, or any third-party rights. Creator expressly acknowledges that PearUp's exercise of this right does not constitute PearUp's assumption of any editorial responsibility for Creator's Content.</p>

      <p style={sectionStyle}>Section 11. Non-Circumvention & Off-Platform Transaction Prohibition</p>
      <p style={body}>With respect to any Introduced Brand — meaning any Brand with which Creator first established contact, communication, or a business relationship through or by means of the Platform — Creator shall not, for a period of twenty-four (24) months following the date of such introduction, directly or indirectly: solicit, accept, initiate, or discuss any business arrangement, engagement, Campaign, content creation service, or any other transaction with the Introduced Brand outside of the Platform; accept any payment, compensation, gift, equity, or consideration of any kind from the Introduced Brand in connection with any services except through the Platform; or share personal contact information (including email addresses, telephone numbers, direct social media handles, personal websites, or any other off-platform contact method) with the Introduced Brand for the purpose of facilitating or enabling off-Platform transactions.</p>
      <p style={body}>In the event of any actual or threatened violation of this Section, PearUp shall be entitled to: immediate termination of Creator's account without notice or refund; liquidated damages equal to the Platform Fee (12%) that PearUp would have earned on the total value of all off-Platform transactions during the restriction period, plus a penalty equal to an additional twelve percent (12%) of such transaction value; recovery of all actual, documented losses suffered by PearUp; injunctive relief; and recovery of all reasonable attorneys' fees, court costs, and expenses. Creator acknowledges that the restrictions in this Section are reasonable in time, scope, and geographic reach given PearUp's business model.</p>

      <p style={sectionStyle}>Section 12. Confidentiality</p>
      <p style={body}>"Confidential Information" means any non-public information disclosed to Creator by PearUp or by any Brand in connection with the Platform or any Campaign, including: Campaign details, pricing, budget information, marketing strategies, advertising performance data, audience data, customer information, Brand business strategies, product development plans, trade secrets, proprietary technology, Platform data and analytics, and PearUp's business relationships.</p>
      <p style={body}>Creator agrees to: hold all Confidential Information in strict confidence; not disclose any Confidential Information to any third party without the prior written consent of the disclosing party; use Confidential Information solely for the purpose of performing Creator's obligations under the applicable Campaign; use at least the same degree of care to protect Confidential Information as Creator uses to protect Creator's own confidential information, and in no event less than reasonable care; and promptly notify PearUp in writing of any unauthorized disclosure or use of Confidential Information.</p>
      <p style={body}>Creator's obligations under this Section survive the termination or expiration of this Agreement for a period of five (5) years. With respect to trade secrets, Creator's confidentiality obligations shall continue for so long as the information constitutes a trade secret under applicable law. These obligations do not apply to information that is or becomes publicly known through no wrongful act of Creator, or that Creator is required to disclose by applicable law or valid court order (with prompt prior written notice to PearUp).</p>

      <p style={sectionStyle}>Section 13. Indemnification</p>
      <p style={body}>To the fullest extent permitted by applicable law, Creator shall defend, indemnify, protect, and hold harmless PearUp and each of its founders, officers, directors, employees, shareholders, investors, affiliates, subsidiaries, licensors, service providers, successors, assigns, and agents from and against any and all claims, demands, suits, proceedings, governmental investigations, losses, liabilities, damages, settlements, judgments, fines, penalties, costs, and expenses (including reasonable attorneys' fees, expert fees, and court costs) arising out of or relating to any of the following:</p>
      <p style={bullet}>— Any Content created, delivered, published, or distributed by Creator, including claims of copyright infringement, trademark infringement, defamation, false light, invasion of privacy, right of publicity violation, or false advertising.</p>
      <p style={bullet}>— Any act, omission, negligence, recklessness, willful misconduct, fraud, or misrepresentation by Creator in connection with Creator's use of the Platform or performance of Services.</p>
      <p style={bullet}>— Any violation of FTC guidelines, consumer protection laws, advertising disclosure requirements, or truth-in-advertising laws by Creator, including any regulatory enforcement action or civil claim arising therefrom.</p>
      <p style={bullet}>— Any infringement or misappropriation by Creator of any third-party Intellectual Property rights, including music licensing violations, unlicensed use of stock assets, and AI-generated Content IP issues.</p>
      <p style={bullet}>— Any violation by Creator of applicable privacy laws, data protection regulations (including GDPR, CCPA, LGPD, or equivalent), or data security requirements.</p>
      <p style={bullet}>— Any failure by Creator to pay any tax, penalty, or interest arising from Creator's income earned through the Platform, including any tax liability, fine, or governmental enforcement action asserted against PearUp arising from Creator's tax non-compliance.</p>
      <p style={bullet}>— Any claim by any governmental authority or third party that Creator is or should be classified as an employee of PearUp.</p>
      <p style={bullet}>— Any breach of any representation, warranty, covenant, or obligation by Creator under this Agreement or any Campaign terms.</p>
      <p style={bullet}>— Any circumvention of the Platform in violation of Section 11 of this Agreement.</p>
      <p style={bullet}>— Any claim arising from Creator's use of fake followers, purchased engagement, bots, or other fraudulent social media practices.</p>
      <p style={bullet}>— Any third-party claim arising from claims or endorsements Creator makes about any Brand's products or services that are false, deceptive, or unsubstantiated.</p>
      <p style={body}>Creator's indemnification obligations include the obligation to assume the defense of any indemnified claim upon PearUp's written request and to advance reasonable legal defense costs to PearUp Parties upon request, without awaiting the outcome of the underlying proceeding. Creator's indemnification obligations survive the termination or expiration of this Agreement.</p>

      <p style={sectionStyle}>Section 14. Limitation of Liability</p>
      <p style={caps}>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL PEARUP OR ANY PEARUP PARTY BE LIABLE TO CREATOR OR ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY, OR ENHANCED DAMAGES OF ANY KIND, INCLUDING: LOSS OF PROFITS, REVENUE, INCOME, OR BUSINESS OPPORTUNITY; LOSS OF DATA, LOSS OF GOODWILL, OR LOSS OF REPUTATION; BUSINESS INTERRUPTION DAMAGES; DAMAGES ARISING FROM CREATOR'S INABILITY TO ACCESS THE PLATFORM; DAMAGES ARISING FROM CAMPAIGN FAILURE, POOR CONTENT PERFORMANCE, OR BRAND DISSATISFACTION; DAMAGES ARISING FROM SOCIAL MEDIA PLATFORM ACCOUNT SUSPENSIONS, BANS, OR ALGORITHM CHANGES; OR REPUTATIONAL DAMAGES OR BRAND DAMAGE OF ANY KIND. THESE EXCLUSIONS APPLY REGARDLESS OF THE LEGAL THEORY AND EVEN IF PEARUP HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
      <p style={caps}>PEARUP'S TOTAL AGGREGATE LIABILITY TO CREATOR FOR ANY AND ALL CLAIMS ARISING UNDER OR RELATING TO THIS AGREEMENT OR THE PLATFORM SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL PLATFORM FEES PAID BY CREATOR DURING THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE DATE ON WHICH THE APPLICABLE CLAIM FIRST AROSE; OR (B) ONE HUNDRED UNITED STATES DOLLARS (USD $100.00).</p>

      <p style={sectionStyle}>Section 15. Privacy, Data Security & Data Compliance</p>
      <p style={body}>Creator represents, warrants, and covenants that Creator's activities on the Platform comply with all applicable privacy and data protection laws, including CCPA/CPRA, GDPR (where applicable), Brazil's LGPD, Colombia's Ley 1581 de 2012, Mexico's LFPDPPP, and all other applicable national, state, or local privacy and data protection laws.</p>
      <p style={body}>Creator agrees to: protect all personal data, user data, audience data, and Brand data received in connection with any Campaign using reasonable and appropriate security measures; not share, sell, license, transfer, or otherwise disclose any personal data received in connection with the Platform or any Campaign to any third party without prior written consent; not use any data received in connection with the Platform or any Campaign for any purpose other than the performance of Creator's obligations under the applicable Campaign; notify PearUp in writing within seventy-two (72) hours of becoming aware of any actual or suspected data security incident; and cooperate fully with PearUp in responding to any data security incident, regulatory inquiry, or enforcement action.</p>
      <p style={body}>Creator shall not scrape, harvest, or extract any data from the Platform using automated means; use Platform data for any purpose other than participating in the Platform's intended marketplace functions; or aggregate, compile, or analyze Platform data for competitive intelligence or any commercial purpose outside the Platform without PearUp's prior written consent.</p>

      <p style={sectionStyle}>Section 16. Account Suspension & Termination</p>
      <p style={body}>PearUp reserves the right, in its sole and absolute discretion and without incurring any liability to Creator, to suspend, restrict, or permanently terminate Creator's account and access to the Platform at any time, with or without notice, for any reason, including: violation of any provision of this Agreement, the Terms of Service, or any Platform policy; actual or suspected fraud, identity misrepresentation, or account manipulation; use of fake followers, purchased engagement, bots, or other fraudulent social media practices; repeated disputes, chargebacks, or non-delivery of agreed Services; any conduct posing legal, regulatory, reputational, or financial risk to PearUp, any Brand, or any other Platform user; circumvention of the Platform in violation of Section 11; breach of Creator's confidentiality obligations; or any governmental, regulatory, or law enforcement request or order requiring suspension or termination.</p>
      <p style={body}>Creator may terminate Creator's account at any time by contacting PearUp. Termination does not relieve Creator of any obligations incurred prior to termination, including obligations under Sections 11 (non-circumvention), 12 (confidentiality), 13 (indemnification), and any outstanding Campaign obligations.</p>
      <p style={body}>Upon termination: Creator's license to use the Platform is immediately revoked; PearUp may remove Creator's profile, Content, and data from the Platform; any escrowed funds for active Campaigns will be handled in accordance with PearUp's dispute resolution policies; the Platform Fee is non-refundable for Campaigns that were active prior to termination.</p>

      <p style={sectionStyle}>Section 17. Dispute Resolution & Governing Law</p>
      <p style={body}>This Agreement is governed by and construed in accordance with the laws of the Commonwealth of Massachusetts, United States of America, without regard to conflict of law provisions.</p>
      <p style={body}>Before initiating any arbitration, the party asserting a dispute shall provide written notice describing the nature of the dispute, the specific relief sought, and the factual basis. The parties shall then negotiate in good faith for thirty (30) days to attempt to resolve the dispute informally. This informal resolution period is a condition precedent to the commencement of arbitration, except where immediate injunctive relief is sought.</p>
      <p style={caps}>ANY DISPUTE, CLAIM, OR CONTROVERSY ARISING OUT OF OR RELATING TO THIS AGREEMENT, THE PLATFORM, OR ANY CAMPAIGN THAT CANNOT BE RESOLVED INFORMALLY SHALL BE RESOLVED EXCLUSIVELY THROUGH FINAL, BINDING INDIVIDUAL ARBITRATION ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION ("AAA") UNDER ITS CONSUMER ARBITRATION RULES (OR COMMERCIAL ARBITRATION RULES WHERE APPLICABLE). ARBITRATION SHALL TAKE PLACE IN BOSTON, MASSACHUSETTS, OR VIA REMOTE HEARING AS PERMITTED BY THE AAA. CREATOR EXPRESSLY AND IRREVOCABLY WAIVES ANY RIGHT TO BRING OR PARTICIPATE IN ANY CLASS ACTION LAWSUIT, CLASS-WIDE ARBITRATION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, MASS ARBITRATION, OR ANY OTHER REPRESENTATIVE OR CONSOLIDATED PROCEEDING AGAINST PEARUP. ALL DISPUTES SHALL BE ARBITRATED ON AN INDIVIDUAL BASIS ONLY. CREATOR ALSO EXPRESSLY AND IRREVOCABLY WAIVES ANY RIGHT TO A JURY TRIAL. The prevailing party in any arbitration shall be entitled to recover reasonable attorneys' fees and costs, as determined by the arbitrator.</p>
      <p style={body}>Notwithstanding the foregoing, either party may seek temporary restraining orders, preliminary injunctions, and other emergency or provisional equitable relief from a court of competent jurisdiction (including for violations of Sections 11 and 12) without waiving the right to arbitration. Any such proceeding shall be brought exclusively in the state or federal courts located in Boston, Massachusetts. Either party may bring an individual claim in small claims court where the claim qualifies.</p>

      <p style={sectionStyle}>Section 18. General Provisions</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Entire Agreement</strong> — This Agreement, together with PearUp's Terms of Service and Privacy Policy, and any Campaign-specific terms agreed upon through the Platform, constitutes the entire agreement between Creator and PearUp with respect to the subject matter hereof and supersedes all prior or contemporaneous agreements, understandings, representations, and negotiations, whether oral or written.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Amendments</strong> — PearUp reserves the right to modify this Agreement at any time. When material changes are made, PearUp will provide notice at least fourteen (14) days prior to the effective date. Creator's continued use of the Platform after the effective date of any amendment constitutes Creator's binding acceptance. If Creator does not agree to the revised Agreement, Creator must immediately discontinue use of the Platform.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Severability</strong> — If any provision is found invalid, illegal, or unenforceable, it shall be modified to the minimum extent necessary, and the remaining provisions continue in full force and effect.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>No Waiver</strong> — PearUp's failure or delay in exercising any right or remedy shall not constitute a waiver. No waiver of any breach constitutes a waiver of any subsequent breach of the same or any other provision.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Assignment</strong> — Creator may not assign, transfer, or delegate any rights or obligations under this Agreement without PearUp's prior written consent. Any purported assignment without such consent is null and void. PearUp may assign its rights and obligations to any successor entity, acquirer, or affiliate without Creator's consent.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Force Majeure</strong> — PearUp shall not be liable for any delay or failure in performance resulting from causes beyond PearUp's reasonable control, including natural disasters, pandemics, governmental actions, internet infrastructure failures, third-party platform outages, cyberattacks, or labor disputes.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Electronic Acceptance</strong> — Clicking "I Agree," completing registration, or otherwise affirmatively accepting this Agreement through electronic means constitutes Creator's legally binding signature to this Agreement, with the same legal effect as a handwritten signature, pursuant to the Electronic Signatures in Global and National Commerce Act (E-SIGN Act) and applicable state electronic signature laws.</p>
      <p style={body}><strong style={{ color: "rgba(255,255,255,0.85)" }}>Contact</strong> — For questions, legal notices, or concerns regarding this Agreement, contact: <span style={{ color: "#c9a96e" }}>legal@pearup.com</span></p>

      <p style={{ fontFamily: "Georgia, serif", fontSize: "13px", color: "rgba(255,255,255,0.35)", margin: "40px 0 0", fontStyle: "italic" }}>BY REGISTERING AS A CREATOR, CLICKING "I AGREE," OR USING THE PLATFORM IN ANY WAY, CREATOR ACKNOWLEDGES THAT CREATOR HAS READ THIS AGREEMENT IN FULL, UNDERSTANDS ITS TERMS, AND AGREES TO BE LEGALLY BOUND BY ALL OF ITS PROVISIONS, INCLUDING THE BINDING ARBITRATION CLAUSE, CLASS ACTION WAIVER, JURY TRIAL WAIVER, LIMITATION OF LIABILITY, AND INDEMNIFICATION OBLIGATIONS.</p>

      <div style={{ borderTop: "1px solid rgba(255,255,255,0.08)", marginTop: "60px", paddingTop: "24px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <p style={{ fontFamily: "Arial", fontSize: "16px", fontWeight: "700", letterSpacing: "4px", color: "#c9a96e", margin: "0" }}>PEARUP</p>
        <a href="/" style={{ fontFamily: "Georgia, serif", fontSize: "13px", color: "rgba(255,255,255,0.35)", textDecoration: "none" }}>← Back to Pearup</a>
      </div>
      <p style={{ fontFamily: "Georgia, serif", fontSize: "12px", color: "rgba(255,255,255,0.2)", margin: "12px 0 0" }}>© 2026 PearUp, LLC. All Rights Reserved.</p>
    </div>
  );
}
